node:
  display_name: "New MeshBan Node"

database:
  path: "./data/meshban.db"

webui:
  listen: "127.0.0.1:30000"
  require_token_for_remote: true

security:
  encrypt_private_key: true

secrets:
  env_file: ".env"

p2p:
  enabled: false
  bootstrap_peers: []

minecraft:
  enabled: true
  default_policy:
    kick_message: "You have been kicked because this server is using MeshBan and you satisfied this server's kick policy: {policy_met}.
                  If you believe this is a mistake, you can contact the server's admin at {support_contact}"
    support_contact: "SUPPORT_CONTACT"  # if such variable cannot be found in .env, this value is used.
    ultimate: 1  # when a player is banned by a node with trust level of "ultimate" 1 time, kick the player
    trusted: 2
    friend: 5
    unknown: 20
    untrusted: 0  # set to 0 to ignore untrusted nodes

  uuid_resolver:  # defautl setting. query uuid from sources other than rcon/adapter, can be used for third-party authenticated players
    enabled: false
    endpoint: "https://api.minecraftservices.com/minecraft/profile/lookup/name/{name}"
    response_uuid_field: "id"
    timeout_seconds: 5
    retry_count: 2
    proxy_type: "none" # Possible choices: none, environment, http, https, socks5
    proxy_url: "PROXY_URL"
    proxy_auth: false
    proxy_username_env: "PROXY_USERNAME"
    proxy_pass_env: "PROXY_PASSWORD"

  instances:
    - id: "survival"
      enabled: true
      mode: "rcon"

      rcon:
        host: "127.0.0.1"
        port: 25575
        password_env: "SURVIVAL_RCON_PASS"
        poll_interval_seconds: 60
        command_timeout_seconds: 3

      log:
        path: "/home/minecraft/survival/logs/latest.log"
        poll_interval_seconds: 1
        read_from_end_on_start: true

      banned_players_path: "/home/minecraft/survival/banned-players.json"

      policy:
        kick_reason: "You are not allowed to join this server."

    - id: "modded"
      enabled: false
      mode: "paper_adapter"
      paper_adapter: "paper"
      adapter_token_env: "MODDED_SERVER_TOEKN"
      policy:  # override default_policy
        unknown: 100
        support_contact: "MODDED_SUPPORT_CONTACT"
      uuid_resolver:  # override default uuid_resolver settings
        enabled: true  # use internal UUID lookup instead of relying on rcon/adapter
